branches:
  only:
  - src
language: node_js
node_js:
  - "node"
before_script:
  - npm install -g gatsby-cli eslint stylelint
script:
  - ./node_modules/.bin/eslint src/**/*.js*
  - stylelint "src/**/*.css"  --di
  - npm run test
before_deploy:
  - npm run build
deploy:
  skip-cleanup: true
  provider: pages
  github-token: $GITHUB_TOKEN
  local-dir: public
  target-branch: master
  keep-history: true
  name: WishxSLOHacks Bot
  on:
    branch: src