branches:
  only:
  - master
language: node_js
node_js:
  - "node"
before_script:
  - npm install -g gatsby-cli eslint stylelint
script:
  - ./node_modules/.bin/eslint src/**/*.js*
  - stylelint "src/**/*.css"  --di
  - npm run test